"""Protocol definition for visualizer implementations."""

from typing import Optional, Protocol


class VisualizerProtocol(Protocol):
    """Protocol for visualizer implementations."""
    async def set_task(self, task: str) -> None: ...
    async def set_nodes(self, nodes: list[dict], phases: list) -> None: ...
    async def update_status(self, node_id: str, status: str) -> None: ...
    async def set_phase(self, phase_num: int) -> None: ...
    async def add_log(self, message: str, level: str = "info", node_id: Optional[str] = None) -> None: ...
    async def select_plan(self, plans: list) -> int: ...
    async def set_workflow_phase(self, phase: str) -> None: ...
