#!/usr/bin/env python3
"""
Multi-Agent Workflow Example

This script demonstrates coordinated multi-agent systems using OpenAI Agents SDK.
It shows how different specialized agents can work together on complex tasks.

Usage:
    python multi_agent_workflow.py
"""

import asyncio
import os
import sys
from typing import List, Dict, Any
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

try:
    from agents import Agent, Runner, function_tool, handoff
    from agents.extensions.models.litellm_model import LitellmModel
except ImportError as e:
    print(f"❌ Import error: {e}")
    print("Please install required packages:")
    print("  pip install 'openai-agents[litellm]' python-dotenv")
    sys.exit(1)

# Function tools for different agents
@function_tool
def research_topic(topic: str) -> str:
    """
    Research a topic and return detailed information.

    Args:
        topic: Topic to research

    Returns:
        Detailed research information
    """
    # In a real implementation, this would call web search APIs
    return f"""
    Research on {topic}:

    Key Findings:
    1. {topic} is a rapidly evolving field with significant impact
    2. Current applications include automation, analytics, and decision support
    3. Future trends point towards increased integration with existing systems

    Sources:
    - Industry reports and academic publications
    - Case studies from leading organizations
    - Expert analysis and predictions
    """

@function_tool
def summarize_text(text: str, max_length: int = 200) -> str:
    """
    Summarize text to specified length.

    Args:
        text: Text to summarize
        max_length: Maximum length of summary

    Returns:
        Concise summary
    """
    # Simple summarization - in reality would use more sophisticated methods
    if len(text) <= max_length:
        return text

    sentences = text.split('. ')
    summary = '. '.join(sentences[:3]) + '.'
    if len(summary) > max_length:
        summary = summary[:max_length].rsplit('. ', 1)[0] + '.'

    return summary

@function_tool
def analyze_sentiment(text: str) -> Dict[str, Any]:
    """
    Analyze sentiment of text.

    Args:
        text: Text to analyze

    Returns:
        Sentiment analysis results
    """
    # Simple sentiment analysis
    positive_words = {"good", "great", "excellent", "positive", "success"}
    negative_words = {"bad", "poor", "negative", "failure", "problem"}

    text_lower = text.lower()
    positive_count = sum(1 for word in positive_words if word in text_lower)
    negative_count = sum(1 for word in negative_words if word in text_lower)

    if positive_count > negative_count:
        sentiment = "positive"
    elif negative_count > positive_count:
        sentiment = "negative"
    else:
        sentiment = "neutral"

    return {
        "sentiment": sentiment,
        "positive_words_found": positive_count,
        "negative_words_found": negative_count,
        "confidence": min(1.0, (abs(positive_count - negative_count) / 10))
    }

@function_tool
def format_report(content: str, format_type: str = "markdown") -> str:
    """
    Format content into a specific report format.

    Args:
        content: Content to format
        format_type: Format type (markdown, html, plain)

    Returns:
        Formatted report
    """
    if format_type == "markdown":
        return f"# Report\n\n{content}\n\n---\n*Generated by Multi-Agent System*"
    elif format_type == "html":
        return f"<html><body><h1>Report</h1><p>{content}</p><hr/><em>Generated by Multi-Agent System</em></body></html>"
    else:
        return f"REPORT\n======\n\n{content}\n\n---\nGenerated by Multi-Agent System"

class MultiAgentSystem:
    """
    Coordinated multi-agent system with specialized agents.
    """

    def __init__(self):
        self.api_key = os.getenv("OPENROUTER_API_KEY")
        if not self.api_key:
            raise ValueError("OPENROUTER_API_KEY environment variable not set")

        self.research_agent = None
        self.summary_agent = None
        self.analysis_agent = None
        self.formatting_agent = None

    async def initialize_agents(self):
        """
        Initialize all specialized agents.
        """
        print("🤖 Initializing Multi-Agent System...")

        # Research Agent - Uses more capable model for comprehensive research
        self.research_agent = Agent(
            name="Research Specialist",
            instructions="""
            You are a research specialist. Your task is to thoroughly research
            topics and provide detailed, comprehensive information.
            Focus on accuracy, depth, and covering all relevant aspects.
            Use the research_topic tool to gather information.
            """,
            model=LitellmModel(
                model="openrouter/anthropic/claude-3-5-sonnet",
                api_key=self.api_key,
                temperature=0.3,
                max_tokens=2000
            ),
            tools=[research_topic],
            max_steps=20
        )

        # Summary Agent - Uses efficient model for summarization
        self.summary_agent = Agent(
            name="Summarization Expert",
            instructions="""
            You are a summarization expert. Your task is to take detailed
            information and create concise, accurate summaries.
            Focus on extracting key points and maintaining clarity.
            Use the summarize_text tool to create summaries.
            """,
            model=LitellmModel(
                model="openrouter/anthropic/claude-3-haiku",
                api_key=self.api_key,
                temperature=0.2,
                max_tokens=500
            ),
            tools=[summarize_text],
            max_steps=10
        )

        # Analysis Agent - Specialized in sentiment and content analysis
        self.analysis_agent = Agent(
            name="Content Analyst",
            instructions="""
            You are a content analyst. Your task is to analyze text for
            sentiment, key themes, and implications.
            Provide insightful analysis and recommendations.
            Use the analyze_sentiment tool for analysis.
            """,
            model=LitellmModel(
                model="openrouter/openai/gpt-4-turbo",
                api_key=self.api_key,
                temperature=0.5,
                max_tokens=1000
            ),
            tools=[analyze_sentiment],
            max_steps=15
        )

        # Formatting Agent - Specialized in report formatting
        self.formatting_agent = Agent(
            name="Report Formatter",
            instructions="""
            You are a report formatting specialist. Your task is to take
            analyzed content and format it into professional reports.
            Focus on clarity, structure, and presentation.
            Use the format_report tool to create formatted reports.
            """,
            model=LitellmModel(
                model="openrouter/google/gemini-2.0-flash-exp",
                api_key=self.api_key,
                temperature=0.4,
                max_tokens=800
            ),
            tools=[format_report],
            max_steps=10
        )

        print("✅ All agents initialized successfully!")

    @handoff(from_agent="Research Specialist", to_agent="Summarization Expert")
    async def research_and_summarize(self, topic: str) -> str:
        """
        Research a topic and create a summary.

        Args:
            topic: Topic to research

        Returns:
            Summary of researched topic
        """
        print(f"🔍 Researching topic: {topic}")
        research_result = await Runner.run(
            self.research_agent,
            f"Research this topic thoroughly: {topic}"
        )

        print(f"📝 Creating summary of research...")
        summary_result = await Runner.run(
            self.summary_agent,
            f"Summarize this research: {research_result.final_output}"
        )

        return summary_result.final_output

    @handoff(from_agent="Summarization Expert", to_agent="Content Analyst")
    async def analyze_summary(self, summary: str) -> Dict[str, Any]:
        """
        Analyze a summary for sentiment and key insights.

        Args:
            summary: Summary to analyze

        Returns:
            Analysis results
        """
        print("📊 Analyzing summary for sentiment and insights...")
        analysis_result = await Runner.run(
            self.analysis_agent,
            f"Analyze this summary: {summary}"
        )

        # Extract sentiment using the tool
        sentiment_analysis = analyze_sentiment(summary)
        return {
            "analysis": analysis_result.final_output,
            "sentiment": sentiment_analysis
        }

    @handoff(from_agent="Content Analyst", to_agent="Report Formatter")
    async def create_final_report(self, topic: str, summary: str, analysis: Dict[str, Any]) -> str:
        """
        Create a final formatted report.

        Args:
            topic: Original research topic
            summary: Research summary
            analysis: Analysis results

        Returns:
            Formatted final report
        """
        print("📄 Formatting final report...")

        report_content = f"""
        Research Topic: {topic}

        Summary:
        {summary}

        Analysis:
        {analysis['analysis']}

        Sentiment Analysis:
        - Sentiment: {analysis['sentiment']['sentiment']}
        - Confidence: {analysis['sentiment']['confidence']:.2f}
        - Positive indicators: {analysis['sentiment']['positive_words_found']}
        - Negative indicators: {analysis['sentiment']['negative_words_found']}
        """

        formatting_result = await Runner.run(
            self.formatting_agent,
            f"Format this content into a professional markdown report: {report_content}"
        )

        return formatting_result.final_output

    async def complete_workflow(self, topic: str):
        """
        Execute complete multi-agent workflow for a topic.

        Args:
            topic: Topic to process through workflow
        """
        print(f"\n🚀 Starting Multi-Agent Workflow for: {topic}")
        print("=" * 60)

        # Step 1: Research
        summary = await self.research_and_summarize(topic)
        print(f"\n✅ Research Summary:\n{summary[:200]}...")

        # Step 2: Analysis
        analysis = await self.analyze_summary(summary)
        print(f"\n✅ Analysis Complete:")
        print(f"   Sentiment: {analysis['sentiment']['sentiment']}")
        print(f"   Confidence: {analysis['sentiment']['confidence']:.2f}")

        # Step 3: Report Generation
        report = await self.create_final_report(topic, summary, analysis)
        print(f"\n✅ Final Report Generated:")
        print("=" * 40)
        print(report)
        print("=" * 40)

        return {
            "topic": topic,
            "summary": summary,
            "analysis": analysis,
            "report": report
        }

async def demonstrate_simple_workflow():
    """
    Demonstrate a simple multi-agent workflow.
    """
    print("🧪 Simple Multi-Agent Workflow Demonstration")
    print("=" * 50)

    # Create agents
    researcher = Agent(
        name="Simple Researcher",
        instructions="Research topics and provide information.",
        model="gpt-4o",
        tools=[research_topic]
    )

    summarizer = Agent(
        name="Simple Summarizer",
        instructions="Summarize information concisely.",
        model="gpt-4o",
        tools=[summarize_text]
    )

    # Sequential workflow
    print("📚 Researching 'Artificial Intelligence'...")
    research_result = await Runner.run(
        researcher,
        "Research artificial intelligence"
    )

    print("📝 Summarizing research...")
    summary_result = await Runner.run(
        summarizer,
        f"Summarize this: {research_result.final_output}"
    )

    print("\n✅ Results:")
    print(f"Research length: {len(research_result.final_output)} characters")
    print(f"Summary length: {len(summary_result.final_output)} characters")
    print(f"\nSummary preview: {summary_result.final_output[:100]}...")

async def demonstrate_parallel_agents():
    """
    Demonstrate multiple agents working in parallel.
    """
    print("\n🔄 Parallel Agent Execution")
    print("=" * 50)

    # Create multiple specialized agents
    agents = {
        "weather": Agent(
            name="Weather Agent",
            instructions="Provide weather information.",
            model="gpt-4o",
            tools=[research_topic]
        ),
        "news": Agent(
            name="News Agent",
            instructions="Provide news summaries.",
            model="gpt-4o",
            tools=[summarize_text]
        ),
        "analysis": Agent(
            name="Analysis Agent",
            instructions="Analyze content.",
            model="gpt-4o",
            tools=[analyze_sentiment]
        )
    }

    # Run agents in parallel
    tasks = []
    for agent_name, agent in agents.items():
        task = Runner.run(
            agent,
            f"Tell me about the current state of {agent_name} using your tools"
        )
        tasks.append(task)

    results = await asyncio.gather(*tasks)

    print("\n📊 Parallel Results:")
    for agent_name, result in zip(agents.keys(), results):
        print(f"\n{agent_name.upper()} Agent:")
        print(f"  Output: {result.final_output[:100]}...")

def main():
    """
    Main entry point for the multi-agent workflow demonstration.
    """
    import argparse

    parser = argparse.ArgumentParser(description="Multi-Agent Workflow Demonstration")
    parser.add_argument(
        "--simple",
        action="store_true",
        help="Demonstrate simple workflow"
    )
    parser.add_argument(
        "--parallel",
        action="store_true",
        help="Demonstrate parallel agents"
    )
    parser.add_argument(
        "--complete",
        action="store_true",
        help="Run complete multi-agent workflow"
    )
    parser.add_argument(
        "--topic",
        type=str,
        default="Artificial Intelligence",
        help="Topic for workflow (default: Artificial Intelligence)"
    )

    args = parser.parse_args()

    # If no arguments, show help
    if not any([args.simple, args.parallel, args.complete]):
        parser.print_help()
        return

    try:
        if args.simple:
            asyncio.run(demonstrate_simple_workflow())

        if args.parallel:
            asyncio.run(demonstrate_parallel_agents())

        if args.complete:
            # Check for OpenRouter API key
            if not os.getenv("OPENROUTER_API_KEY"):
                print("❌ OPENROUTER_API_KEY environment variable not set")
                print("💡 Set it with: export OPENROUTER_API_KEY='your-key'")
                return

            system = MultiAgentSystem()
            asyncio.run(system.initialize_agents())
            result = asyncio.run(system.complete_workflow(args.topic))

            print("\n" + "=" * 60)
            print("🎉 Multi-Agent Workflow Complete!")
            print("=" * 60)
            print(f"\n📈 Workflow Statistics:")
            print(f"   Topic: {result['topic']}")
            print(f"   Summary Length: {len(result['summary'])} characters")
            print(f"   Report Length: {len(result['report'])} characters")
            print(f"   Sentiment: {result['analysis']['sentiment']['sentiment']}")

    except KeyboardInterrupt:
        print("\n\n👋 Demonstration cancelled by user.")
    except Exception as e:
        print(f"\n❌ Error during demonstration: {e}")
        import traceback
        traceback.print_exc()

if __name__ == "__main__":
    main()